CREATE DATABASE COMPANY_INFORMATION;

USE COMPANY_INFORMATION;

CREATE TABLE SALSEPERSON(
SNo INT PRIMARY KEY,
SNAME VARCHAR(20),
CITY VARCHAR(10),
COMM FLOAT);

INSERT INTO SALSEPERSON VALUES(1001, "Peel", "London", .12);
INSERT INTO SALSEPERSON VALUES(1002, "serres", "San Jose", .13);
INSERT INTO SALSEPERSON VALUES(1004, "Motika", "London", .11);
INSERT INTO SALSEPERSON VALUES(1007, "Rafkin", "Barcelona", .15);
INSERT INTO SALSEPERSON VALUES(1003, "AxelRod", "New york", .1);

SELECT * FROM SALSEPERSON;

CREATE TABLE CUSTOMER(
CNM INT PRIMARY KEY,
CNAME VARCHAR(20),
CITY VARCHAR(10),
RATING INT,
SNO INT,
FOREIGN KEY (SNo) REFERENCES SALSEPERSON (SNo));

INSERT INTO CUSTOMER VALUES (201, "Hoffman","London", 100, 1001);
INSERT INTO CUSTOMER VALUES (202, "Giovanne","Roe", 200, 1003);
INSERT INTO CUSTOMER VALUES (203, "Liu","San Jose", 300, 1002);
INSERT INTO CUSTOMER VALUES (204, "Grass", "Barcelona", 100, 1002);
INSERT INTO CUSTOMER VALUES (206, "Clements", "London", 300, 1007);
INSERT INTO CUSTOMER VALUES (207, "Pereira", "Roe", 100, 1004);

SELECT * FROM CUSTOMER;

SELECT SNAME,CITY FROM SALSEPERSON WHERE CITY="London" AND COMM >=.12;
SELECT * FROM SALSEPERSON WHERE CITY IN ("Barcelona", "London");
SELECT SNo, SNAME, COMM FROM SALSEPERSON WHERE COMM between 0.10 AND 0.12; 
SELECT * FROM CUSTOMER WHERE Rating >=100 or CITY ="Roe";